# Generated by Django 4.2.6 on 2023-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_studentprofile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('processing', 'processing'), ('shortlisted', 'shortlisted')], default='applied', max_length=200),
        ),
    ]
